version: '3.7'
configs:
  telegraf_config:
    file: ./telegraf.conf
services:
  influxdb:
    image: "influxdb:2"
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=bzO10KmR8x
    networks:
      - network
  telegraf:
    image: "telegraf:latest"
    ports:
      - "4317:4317"
    configs:
      - source: telegraf_config
        target: /etc/telegraf/telegraf.conf
    networks:
      - network

  etcd-server:
    image: bitnamilegacy/etcd:3
    container_name: etcd-server
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    restart: unless-stopped
    networks:
      - network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data
    command: -js -sd /data -m 8222
    restart: unless-stopped
    networks:
      - network

  railway-crossing-services:
    image: railway-services:latest
    container_name: railway-crossing-services
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
    depends_on:
      - telegraf
      - etcd-server
      - nats
    networks:
      - network

volumes:
  influxdb_data:
  etcd_data:
  nats_data:

networks:
  network:
    external: true