x-worker-base: &worker-base
  image: collaborativestatemachines/cirrina:unstable
  pull_policy: always
  depends_on:
    - arbiter

services:
  arbiter:
    image: collaborativestatemachines/cirrina:unstable
    build:
      context: .
    environment:
      - RUN=arbiter
    volumes:
      - ./:/app
      - ./metrics_arbiter:/metrics

  w0:
    <<: *worker-base
    environment: { RUN: 0 }
    volumes:
      - ./:/app
      - ./metrics_w0:/metrics

  w1:
    <<: *worker-base
    environment: { RUN: 1 }
    volumes:
      - ./:/app
      - ./metrics_w1:/metrics

  w2:
    <<: *worker-base
    environment: { RUN: 2 }
    volumes:
      - ./:/app
      - ./metrics_w2:/metrics
