# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'Event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ContextVariable_pb2 as ContextVariable__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x45vent.proto\x12\x08\x65xchange\x1a\x15\x43ontextVariable.proto\"\xed\x01\n\x05\x45vent\x12\r\n\x05topic\x18\x01 \x01(\t\x12(\n\x07\x63hannel\x18\x02 \x01(\x0e\x32\x17.exchange.Event.Channel\x12\'\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x19.exchange.ContextVariable\x12\x0e\n\x06target\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\n\n\x02id\x18\x06 \x01(\t\x12\x13\n\x0b\x63reatedTime\x18\x07 \x01(\x03\"A\n\x07\x43hannel\x12\x0c\n\x08INTERNAL\x10\x00\x12\x0c\n\x08\x45XTERNAL\x10\x01\x12\n\n\x06GLOBAL\x10\x02\x12\x0e\n\nPERIPHERAL\x10\x03\x42\x41\n0at.ac.uibk.dps.cirrina.execution.object.exchangeB\x0b\x45ventProtosP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0at.ac.uibk.dps.cirrina.execution.object.exchangeB\013EventProtosP\000'
  _globals['_EVENT']._serialized_start=49
  _globals['_EVENT']._serialized_end=286
  _globals['_EVENT_CHANNEL']._serialized_start=221
  _globals['_EVENT_CHANNEL']._serialized_end=286
# @@protoc_insertion_point(module_scope)
