x-worker-base: &worker-base
  image: collaborativestatemachines/cirrina:unstable
  pull_policy: always
  depends_on:
    - mall

services:
  mall:
    image: collaborativestatemachines/cirrina:unstable
    pull_policy: always
    environment:
      - RUN=mall
    volumes:
      - ./:/app
      - ./metrics_mall:/metrics
  w0:
    <<: *worker-base
    environment: { RUN: 0 }
    volumes:
      - ./:/app
      - ./metrics_w0:/metrics

  w1:
    <<: *worker-base
    environment: { RUN: 1 }
    volumes:
      - ./:/app
      - ./metrics_w1:/metrics

  w2:
    <<: *worker-base
    environment: { RUN: 2 }
    volumes:
      - ./:/app
      - ./metrics_w2:/metrics

  w3:
    <<: *worker-base
    environment: { RUN: 3 }
    volumes:
      - ./:/app
      - ./metrics_w3:/metrics

  w4:
    <<: *worker-base
    environment: { RUN: 4 }
    volumes:
      - ./:/app
      - ./metrics_w4:/metrics

  w5:
    <<: *worker-base
    environment: { RUN: 5 }
    volumes:
      - ./:/app
      - ./metrics_w5:/metrics

  w6:
    <<: *worker-base
    environment: { RUN: 6 }
    volumes:
      - ./:/app
      - ./metrics_w6:/metrics

  w7:
    <<: *worker-base
    environment: { RUN: 7 }
    volumes:
      - ./:/app
      - ./metrics_w7:/metrics

  w8:
    <<: *worker-base
    environment: { RUN: 8 }
    volumes:
      - ./:/app
      - ./metrics_w8:/metrics

  w9:
    <<: *worker-base
    environment: { RUN: 9 }
    volumes:
      - ./:/app
      - ./metrics_w9:/metrics

  w10:
    <<: *worker-base
    environment: { RUN: 10 }
    volumes:
      - ./:/app
      - ./metrics_w10:/metrics

  w11:
    <<: *worker-base
    environment: { RUN: 11 }
    volumes:
      - ./:/app
      - ./metrics_w11:/metrics
