x-worker-base: &worker-base
  image: cirrina
  build:
    context: .
  depends_on:
    - arbitrator
  volumes:
    - ./:/app

services:
  arbitrator:
    image: cirrina
    build:
      context: .
    environment:
      - RUN=arbitrator
    volumes:
      - ./:/app

  w0:
    <<: *worker-base
    environment: { RUN: 0 }

  w1:
    <<: *worker-base
    environment: { RUN: 1 }

  w2:
    <<: *worker-base
    environment: { RUN: 2 }

  w3:
    <<: *worker-base
    environment: { RUN: 3 }

  w4:
    <<: *worker-base
    environment: { RUN: 4 }

  w5:
    <<: *worker-base
    environment: { RUN: 5 }
