apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "railway-crossing.fullname" . }}-services
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "railway-crossing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: services
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: services
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.services.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.services.nodeSelector | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - services
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: services
          image: "{{ .Values.services.image.repository }}:{{ .Values.services.image.tag }}"
          env:
{{- if .Values.services.extraEnvVars }}
{{- toYaml .Values.services.extraEnvVars | nindent 12 }}
{{- end }}
