namespace: default

nats:
  jetstream:
    enabled: true

cirrina:
  image:
    tag: sha-f084ad5
    pullPolicy: Always
  appPath: "https://raw.githubusercontent.com/CollaborativeStateMachines/Cirrina-Examples/refs/heads/develop/railway-crossing/main.pkl"
  serviceBindingsPath: "https://raw.githubusercontent.com/CollaborativeStateMachines/Cirrina-Examples/refs/heads/develop/railway-crossing/services.pkl"
  instantiate: bell,gate,light,controller
  natsEventUrl: nats://railway-crossing-nats:4222/
  natsContextUrl: nats://railway-crossing-nats:4222/
  extraEnvVars:
    - name: OTEL_METRIC_EXPORT_INTERVAL
      value: "1000"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://railway-crossing-telegraf:4317/

services:
  replicas: 1
  image:
    repository: marlonetheredgeuibk/railway-crossing-services
    tag: latest
  extraEnvVars:
    - name: OTEL_METRIC_EXPORT_INTERVAL
      value: "1000"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://railway-crossing-telegraf:4317/

simulateSensors:
  image:
    repository: marlonetheredgeuibk/railway-crossing-simulate-sensors
    tag: latest
  natsUrl: nats://railway-crossing-nats:4222/
  startIntervalSeconds: 0.1
  endIntervalSeconds: 0.01
  extraEnvVars:
  - name: OTEL_METRIC_EXPORT_INTERVAL
    value: "1000"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://railway-crossing-telegraf:4317/