services:
  counter:
    image: collaborativestatemachines/cirrina:unstable
    pull_policy: always
    environment:
      - RUN=counter
    volumes:
      - ./:/app
      - ./metrics_counter:/metrics

  producer:
    image: collaborativestatemachines/cirrina:unstable
    pull_policy: always
    environment:
      - RUN=producer
    depends_on:
      - counter
    volumes:
      - ./:/app
      - ./metrics_producer:/metrics